let name = "Arun";
let school = "ABC School";
let grade = "12th";
let section = "B";
let rollno = 10;
let english = 85;
let maths = 98;
let science = 95;
console.log("************REPORT CARD************");
console.log("School---",school);
console.log("Name----",name);
console.log("Grade----",grade);
console.log("Section----",section);
console.log("Roll No---",rollno);
console.log("English---",english);
console.log("Maths-----",maths);
console.log("Science---",science);
console.log("************************************");